// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhnmjpdgkpxjpbnsyuxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJobm1qcGRna3B4anBibnN5dXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMzAxMzYsImV4cCI6MjA2NTYwNjEzNn0.rz9jxVOiNv1ZMOaS5_AwHTpUIXwYpdqWV3IR7Iw37uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);